/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securesafeguardsystem;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author Khatriman
 */
public class MainFrame extends javax.swing.JFrame implements ActiveUser{

    /**
     * Creates new form MainFrame
     */
    
     SoftwareDB softwareDB;
    
    String path;
    String softName;
    String password;
    String name; 
    
    public MainFrame() {
        initComponents();
        activeuser.setText(active[0]+"  !!!");
        vaultPanel.setVisible(false);
        exePanel.setVisible(false);
        aboutUsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sideDrawer = new javax.swing.JPanel();
        SoftwareName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        activeuser = new javax.swing.JLabel();
        btn_exePanel = new javax.swing.JButton();
        btn_profile_Panel = new javax.swing.JButton();
        btn_vaultPanel = new javax.swing.JButton();
        btn_homePanel = new javax.swing.JButton();
        vaultPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        docButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        exePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filePathTF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        aboutUsPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1300, 773));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideDrawer.setBackground(new java.awt.Color(54, 33, 79));
        sideDrawer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SoftwareName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SoftwareName.setForeground(new java.awt.Color(255, 255, 255));
        SoftwareName.setText("Secure Safe ");
        sideDrawer.add(SoftwareName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guard System");
        sideDrawer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, 60));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("_____________________________");
        sideDrawer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Welcome");
        sideDrawer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 120, 40));

        activeuser.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        activeuser.setForeground(new java.awt.Color(255, 204, 204));
        sideDrawer.add(activeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 220, 30));

        btn_exePanel.setBackground(new java.awt.Color(85, 65, 118));
        btn_exePanel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_exePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exe_exepanel60px.png"))); // NOI18N
        btn_exePanel.setText("Exe Lock");
        btn_exePanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_exePanel.setMaximumSize(new java.awt.Dimension(216, 72));
        btn_exePanel.setMinimumSize(new java.awt.Dimension(216, 72));
        btn_exePanel.setPreferredSize(new java.awt.Dimension(216, 72));
        btn_exePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exePanelActionPerformed(evt);
            }
        });
        sideDrawer.add(btn_exePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 220, 80));

        btn_profile_Panel.setBackground(new java.awt.Color(85, 65, 118));
        btn_profile_Panel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_profile_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus_60px.png"))); // NOI18N
        btn_profile_Panel.setText("ABOUT US");
        btn_profile_Panel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_profile_Panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profile_PanelActionPerformed(evt);
            }
        });
        sideDrawer.add(btn_profile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 220, 80));

        btn_vaultPanel.setBackground(new java.awt.Color(85, 65, 118));
        btn_vaultPanel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_vaultPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/security_lock_60px.png"))); // NOI18N
        btn_vaultPanel.setText("Vault");
        btn_vaultPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_vaultPanel.setMaximumSize(new java.awt.Dimension(216, 72));
        btn_vaultPanel.setMinimumSize(new java.awt.Dimension(216, 72));
        btn_vaultPanel.setPreferredSize(new java.awt.Dimension(216, 72));
        btn_vaultPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaultPanelActionPerformed(evt);
            }
        });
        sideDrawer.add(btn_vaultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 220, 80));

        btn_homePanel.setBackground(new java.awt.Color(85, 65, 118));
        btn_homePanel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_homePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile_60px.png"))); // NOI18N
        btn_homePanel.setText("Profile");
        btn_homePanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_homePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homePanelActionPerformed(evt);
            }
        });
        sideDrawer.add(btn_homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, 80));

        mainPanel.add(sideDrawer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 410, 780));

        vaultPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(122, 72, 180));

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        topLabel.setForeground(new java.awt.Color(255, 255, 255));
        topLabel.setText("Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        imageButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        imageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gallery_60px.png"))); // NOI18N
        imageButton.setText("Images");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        videoButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/video_call_60px.png"))); // NOI18N
        videoButton.setText("Video");
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });

        docButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        docButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doc_60px.png"))); // NOI18N
        docButton.setText("Docs");
        docButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docButtonActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/audio_60px.png"))); // NOI18N
        jButton7.setText("Audios");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vaultPanelLayout = new javax.swing.GroupLayout(vaultPanel);
        vaultPanel.setLayout(vaultPanelLayout);
        vaultPanelLayout.setHorizontalGroup(
            vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaultPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vaultPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(403, 403, 403))
        );
        vaultPanelLayout.setVerticalGroup(
            vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaultPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addGroup(vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        mainPanel.add(vaultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 990, 770));

        exePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(122, 72, 180));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exe Lock");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exe_exepanel60px.png"))); // NOI18N
        jButton2.setText("Add EXE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("File Path : ");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exePanelLayout = new javax.swing.GroupLayout(exePanel);
        exePanel.setLayout(exePanelLayout);
        exePanelLayout.setHorizontalGroup(
            exePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(exePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filePathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );
        exePanelLayout.setVerticalGroup(
            exePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exePanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(exePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filePathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        mainPanel.add(exePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 990, 770));

        aboutUsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("_-_OUR MISSON_-_");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutUsPanelLayout = new javax.swing.GroupLayout(aboutUsPanel);
        aboutUsPanel.setLayout(aboutUsPanelLayout);
        aboutUsPanelLayout.setHorizontalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
            .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutUsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        aboutUsPanelLayout.setVerticalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutUsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(aboutUsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 990, 770));

        jPanel1.setBackground(new java.awt.Color(122, 72, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 990, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_exePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exePanelActionPerformed
        // TODO add your handling code here:
        exePanel.setVisible(true); 
        vaultPanel.setVisible(false);
        aboutUsPanel.setVisible(false);
        //topLabel.setText(" EXE");
        
        
    }//GEN-LAST:event_btn_exePanelActionPerformed

    private void btn_vaultPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaultPanelActionPerformed
        // TODO add your handling code here:     
        vaultPanel.setVisible(true); 
        jPanel1.setVisible(true);
        exePanel.setVisible(false);
        aboutUsPanel.setVisible(false);
        topLabel.setText(" Vault");
        
    }//GEN-LAST:event_btn_vaultPanelActionPerformed

    private void btn_homePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homePanelActionPerformed
        // TODO add your handling code here:
        
        vaultPanel.setVisible(false);
        exePanel.setVisible(false);
        aboutUsPanel.setVisible(false);
        jPanel1.setVisible(true);
        topLabel.setText(" Home");
    }//GEN-LAST:event_btn_homePanelActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        checkClick[0] =0; //for move() function path decider
        EncryptImage encryptImage = new EncryptImage();
        encryptImage.setVisible(true);
        
      
        
    }//GEN-LAST:event_imageButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code he
        
          JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
  
            // invoke the showsSaveDialog function to show the save dialog 
            int r = j.showSaveDialog(null); 
  
            // if the user selects a file 
            if (r == JFileChooser.APPROVE_OPTION) 
  
            { 
                // set the label to the path of the selected file 
                filePathTF.setText(j.getSelectedFile().getAbsolutePath()); 
            } 
            // if the user cancelled the operation 
            else
                filePathTF.setText("the user cancelled the operation"); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        checkClick[0] = 1; //for move() function path decider
        EncryptVideo E = new EncryptVideo();
        E.setVisible(true);
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_videoButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        EncryptVideo V = new EncryptVideo();
        V.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_profile_PanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profile_PanelActionPerformed
        // TODO add your handling code here:
        aboutUsPanel.setVisible(true);
        vaultPanel.setVisible(false);
        exePanel.setVisible(false);
        jPanel1.setVisible(true);
        topLabel.setText(" Profile");

    }//GEN-LAST:event_btn_profile_PanelActionPerformed

    private void docButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docButtonActionPerformed
        // TODO add your handling code here:
        EncryptDocs D = new EncryptDocs();
        D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_docButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        softwareDB = new SoftwareDB();

        path = filePathTF.getText();

        name = path.substring(path.lastIndexOf("\\") + 1, path.indexOf('.'));
            softName = name+".exe" ;

            System.out.println(""+softName);

            try {
                softwareDB.insertIntoSoftPathDB(softName, path);
                 JOptionPane.showMessageDialog(jPanel1,"Exe Lock","Done !!!",JOptionPane.ERROR_MESSAGE);
                
                
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
        
        
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SoftwareName;
    private javax.swing.JPanel aboutUsPanel;
    private javax.swing.JLabel activeuser;
    private javax.swing.JButton btn_exePanel;
    private javax.swing.JButton btn_homePanel;
    private javax.swing.JButton btn_profile_Panel;
    private javax.swing.JButton btn_vaultPanel;
    private javax.swing.JButton docButton;
    private javax.swing.JPanel exePanel;
    private javax.swing.JTextField filePathTF;
    private javax.swing.JButton imageButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sideDrawer;
    private javax.swing.JLabel topLabel;
    private javax.swing.JPanel vaultPanel;
    private javax.swing.JButton videoButton;
    // End of variables declaration//GEN-END:variables
}
